### ISSUE TITLE
SyntaxError: only named arguments may follow *expression

### ISSUE THREAD

**Issue by wangyarui** [ncondo/CarND-Semantic-Segmentation#1]
when I run **python main.py**

Some errors occur like these:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import helper
  File "/home/richal/code/CarND-Semantic-Segmentation/helper.py", line 91
    gt_bg = gt_bg.reshape(*gt_bg.shape, 1)
SyntaxError: only named arguments may follow *expression

But I have installed it by**sudo pip install helper**and **sudo pip install request**in fact. Please,help,thank U

**Comment by AlisonZW** [comment]
me too

I have the same problem!
